### ISSUE TITLE
Document COSIGN_PASSWORD

### ISSUE THREAD

**Issue by imjasonh** [sigstore/docs#113]
**Description**

https://github.com/sigstore/docs/pull/94 removed documentation for the `COSIGN_PASSWORD` environment variable. This is useful documentation that should go somewhere.

@jonvnadelberg @ltagliaferri

**Comment by haydentherapper** [comment]
It is documented under key generation - https://github.com/sigstore/docs/blob/f4b0300196d6a9f6414914e5f3be611f4d575c6f/content/en/cosign/key-generation.md?plain=1#L17

Is that sufficient for this? I think it's reasonable to not be a part of the quickstart guide, as it only has to do with key generation.

**Comment by imjasonh** [comment]
[So it is!](https://docs.sigstore.dev/cosign/key-generation/) Thanks for that.

I did try to search for `COSIGN_PASSWORD` on the site, and it only suggested [Policy Controller > Sample Policies](https://docs.sigstore.dev/policy-controller/sample-policies/), which only mentions it in passing

<img width="450" alt="Screenshot 2023-04-06 at 9 22 58 AM" src="https://user-images.githubusercontent.com/210737/230391403-4f0ce0a3-fd26-49a9-a369-141c2d25a31b.png">

**Comment by haydentherapper** [comment]
I’ve noticed search doesn’t work well, wonder if there’s a substitute

**Comment by ltagliaferri** [comment]
Yeah, I would like to move the site off of Nuxt (maybe Hugo) with a better search, but we'll need to scope and prioritize it against the work we need to do on the docs themselves. There are a lot of issues with the theme's versions.
