### ISSUE TITLE
Docs shows an outdated view

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/docs#114]
Side bar view of docs.sigstore.dev in browser:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/8418760/230509859-e2dcf764-f1c1-4dab-97f9-d24a0ec8bac3.png">

View in incognito:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/8418760/230509922-cfe16c8c-0f5d-41b2-998c-71c4c4921ce3.png">

If I were to guess, page caching is too long-lived. Is this something that is controllable?

**Comment by Pritishchugh22** [comment]
Dear @ltagliaferri @haydentherapper 
I am writing this to express my interest in participating in the Google Season of Docs program, 2023. I am a final year student at IIT Mandi, pursuing Bachelors of Technology in Computer Science. I am doing minors in Data Science and have done a significant number of courses as well as projects in this domain.

Could you please guide me on how to proceed. I would appreciate any advice or recommendations you may have regarding the project.
Regards
Pritish Chugh

**Comment by haydentherapper** [comment]
Done, closing as a dup of https://github.com/sigstore/docs/issues/43
