### ISSUE TITLE
Bug: Broken link readme.md

### ISSUE THREAD

**Issue by maveraw** [sigstore/docs#132]
**Description**

![image](https://user-images.githubusercontent.com/84138882/232478913-eb953bac-2bcb-46bb-8ca7-dee924f4da42.png)
Here this link won't work. Either provide a correct path or it could be just "core sigstore website-team" without any link. It's not mandatory to know theteam.

**Comment by Queen-codes** [comment]
Hi @maveraw . Since a PR has already being merged for this issue, can this issue be closed?
