### ISSUE TITLE
Add Policy controller to Main Concepts

### ISSUE THREAD

**Issue by hrittikhere** [sigstore/docs#133]
Do we want to add policy controller to Main concepts like we did here at https://github.com/sigstore/sigstore-website/issues/258?
The file required to change: 

https://github.com/sigstore/docs/blob/7d3855f3c004b5bb46ce51c42dad0eaa8e936e32/content/en/main-concepts.md?plain=1#L6-L11

**Comment by hrittikhere** [comment]
@ltagliaferri 👀

**Comment by ltagliaferri** [comment]
You're welcome to open a PR
