### ISSUE TITLE
docs: typos: mising parenthesis in heading of Measuring your project’s success of wiki page

### ISSUE THREAD

**Issue by bhartik021** [sigstore/docs#134]
**Description**

There is mising parenthesis. closing  parenthesis should be there in heading of Measuring your project’s success of wiki page.

**Comment by ggold7046** [comment]
Could you please guide me to the wiki page of `Measuring your project’s success`? I could not find it.

**Comment by smythp** [comment]
Hi, I found the page referred to (the SigStore Summer of Docs page on the wiki) and created a commit that resolves the issue by adding a parenthesis.

On GitHub, wikis are their own separate repo, and they don't support PRs. I also don't have access to the wiki to make direct edits. 

If someone has access to the wiki, they can pull in my commit with these steps:

1. Clone the wiki locally with this link: https://github.com/sigstore/docs.wiki.git`
2. Add my manual fork of the repo as a remote: https://github.com/smythp/sigstore-docs-wiki
3. Git pull the commit from my manual fork.
4. Push the updated repo back to the SigStore wiki repo

If that's too much Git for one commit, the wiki page is here:

https://github.com/sigstore/docs/wiki/Season-of-Docs-2023-Organization-Project-Proposal#measuring-your-projects-success

and the text is:

```
Decrease the amount of drifting-away contributors (based on Linux Foundation Insights
```

**Comment by smythp** [comment]
I have added the parenthesis. You can see the revision here:

https://github.com/sigstore/docs/wiki/Season-of-Docs-2023-Organization-Project-Proposal/_history


GitHub Wikis seem only half implemented, so I can't link to the commit. But rest assured, the parenthesis is now present!
