### ISSUE TITLE
Not able to apply for Season of Docs 2023

### ISSUE THREAD

**Issue by Abhi6722** [sigstore/docs#147]
**Description**

When I am trying to apply for Season of Docs 2023 the link is not working and showing an issue

```
Your connection is not private
Attackers might be trying to steal your information from links.sigstore.dev (for example, passwords, messages or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_AUTHORITY_INVALID
```
<img width="1440" alt="Screenshot 2023-04-22 at 11 35 09 AM" src="https://user-images.githubusercontent.com/62201123/233765916-c00d6388-4e66-4fc3-a680-203e55b53726.png">

Please provide me with the correct link to apply.

**Comment by Queen-codes** [comment]
Hi @Abhi6722 .I don't know if you are on the docs channel in the slack workspace but Lisa provided the link to the Google doc itself in order to avoid this issue.

**Comment by Queen-codes** [comment]
The application closed some days back, too.

**Comment by haydentherapper** [comment]
Application has closed, so closing issue.
