### ISSUE TITLE
Enhance sigstore Docs Tasks List

### ISSUE THREAD

**Issue by sandipanpanda** [sigstore/docs#148]
**Description**

As I get familiar with the sigstore project and its community, I am keeping a friction log of any obstacles, challenges, or inconsistencies I encounter. This log will help me identify pain points in the onboarding process and suggest improvements.

- [ ] Improve the About section of sigstore subprojects
  - Add a documentation website link in the Website field of sigstore subprojects
    Outcome: This will make the project documentation easily accessible
  - Update description
    Outcome: This will let people who are looking at the project for the first time get a quick idea of the purpose of the project
  - Add topics
    Outcome: This will improve the discovery of the project on github
    Repositories to update:
    - https://github.com/sigstore/cosign
    - https://github.com/sigstore/fulcio
    - https://github.com/sigstore/rekor
    - https://github.com/sigstore/policy-controller

- [ ]  Update [How sigstore works](https://docs.sigstore.dev/#how-sigstore-works) in Docs
Looking from the perspective of a new user at the project: `How sigstore works` is explained in a better way in https://www.sigstore.dev/how-it-works with diagrams and considering different user perspectives than in https://docs.sigstore.dev/#how-sigstore-works
We can link to it on the documentation website under How Sigstore works and remove the duplicate information from https://docs.sigstore.dev/#how-sigstore-works

- [ ] Use consistent naming to refer to sigstore
I see multiple instances where sigstore is capitalised, though it is instructed otherwise in https://docs.sigstore.dev/contributing/#website-content. Identify and update all pages to use the same nomenclature.

- [ ] Improve visibility about the project [Sigstore and Programming Language Communities](https://docs.sigstore.dev/history/#sigstore-and-programming-language-communities) and [Resources for Learning More](https://docs.sigstore.dev/history/#resources-for-learning-more)
  - Move this information from  [History and Research](https://docs.sigstore.dev/history/) to https://docs.sigstore.dev/ for better visibility to new users
  - Add Securing Your Software Supply Chain with Sigstore Course to [Resources for Learning More](https://docs.sigstore.dev/history/#resources-for-learning-more)

- [ ] Reorganize the docs into the four categories to make them more organized and discoverable for beginners and experienced users, namely:
  - Tutorials
  - How-Tos
  - Reference Guide
  - Explanations
  
    ![image](https://user-images.githubusercontent.com/87253083/234045428-76a3535d-16d9-4b51-adae-8c1e1c6619ac.png)
    Ref: https://documentation.divio.com/

**Comment by sandipanpanda** [comment]
I am willing to help the community in improving the consistency and readability of documentation and work on the aforementioned points. I would highly appreciate any thoughts and feedback from [@ltagliaferri](https://github.com/ltagliaferri) and other community members on this.

**Comment by ltagliaferri** [comment]
I'll give feedback on each task

1. Improve the About section of sigstore subprojects — you can go ahead with this
2. Update [How sigstore works](https://docs.sigstore.dev/#how-sigstore-works) in Docs — the docs are more developer-oriented than the marketing website (more general public oriented). I would not change this at this time, but we can add policy-controller
3.  Use consistent naming to refer to sigstore — we are using "Sigstore" now (we need updated style guides), so there can be consistency towards the title case
4. Improve visibility about the project [Sigstore and Programming Language Communities](https://docs.sigstore.dev/history/#sigstore-and-programming-language-communities) and [Resources for Learning More](https://docs.sigstore.dev/history/#resources-for-learning-more) — I don't think we should move history and research to the home page, if that's what you meant? The Linux Foundation course is not considered part of the Sigstore community so I would avoid including that here right now.
5. Reorganize the docs into the four categories to make them more organized and discoverable for beginners and experienced users, namely: — Let's not reorganize based on genre of doc, the organization based on project makes sense to me

**Comment by sandipanpanda** [comment]
@ltagliaferri sorry if I could not get my point across. Only the organisation owners have permission to edit the About section of a repository (indicated by a gear icon around beside `About` around the top right corner of a repository), so I am unable to do that on behalf of Sigstore.

> we are using "Sigstore" now (we need updated style guides), so there can be consistency towards the title case

I'll make a PR to update the outdated style guide on branded terms.
