### ISSUE TITLE
docs: Integrate some content of keyless.md into overview.md 

### ISSUE THREAD

**Issue by jonvnadelberg** [sigstore/docs#155]
**Description**

some parts of keyless.md need to be integrated into the overview.md file as it now exists.

**Comment by Bhardwaj-Himanshu** [comment]
Hi @jonvnadelberg,
Could you also point on the points or topics which need to be moved from one file to another?
Thanks!

**Comment by jonvnadelberg** [comment]
Chiefly the ttl.sh information that gives a good example  of signing with containeres.

**Comment by Bhardwaj-Himanshu** [comment]
So I took a look at both **keyless.md and overview.md**

Keyless section explains in detail about the keyless sign-in, while overview.md gives a complete overview of all the methods to sign in.

So I forked the repo and added over 60 lines, from keyless.md, starting from the headline `this page talks in detail about keyless sign-in` and moved it to `overview.md`--> *the whole keyless signing section* (can't even tag the code too, as it is a markdown file*

Not opening a pull request cause I want to discuss if we need to remove/add something else and even your thoughts on how to do the same?

Thanks

**Comment by haydentherapper** [comment]
@Bhardwaj-Himanshu, this issue is already being worked on by Jon. See the open PR #156

**Comment by Bhardwaj-Himanshu** [comment]
Thanks for letting me know @haydentherapper
I'll move to #156 if I could provide any help on the issue.
Also, send me some of your songs if you do rap-->looking at your username;)
