### ISSUE TITLE
Error: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode

### ISSUE THREAD

**Issue by zishen** [sigstore/docs#165]
**Description**
When I sign a binary file, use "cosign sign-blob kubectl --output-certificate cert.pem --output-signature cert.sig".
It comes ok. But it is not same in verify:
`
root@zishen:/home/btg/install/cosign/image# cosign verify-blob kubectl  --signature cert.sig --certificate cert.pem  
Error: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
main.go:74: error during command execution: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
`
I search doc, it few to tell me, how to verify a binary.
**Version**

So, how to  verify a binary at local?

**Comment by jonvnadelberg** [comment]
This is explained on the verifying page located at https://docs.sigstore.dev/cosign/verify/

**Comment by zishen** [comment]
> This is explained on the verifying page located at https://docs.sigstore.dev/cosign/verify/ and in the overview at https://docs.sigstore.dev/cosign/overview/

Thanks, I was sccueed by using :
cosign verify-blob kubectl --bundle cosign.bundle --certificate-identity=xxx@xx.com --certificate-oidc-issuer=https://github.com/login/oauth
