### ISSUE TITLE
Dead link: oidc-in-fulcio.md

### ISSUE THREAD

**Issue by tylerauerbeck** [sigstore/docs#17]
The `OID Information` link here: https://github.com/sigstore/docs/blob/ba2468317377e448cdda4b8a51500cf3d700b662/content/en/fulcio/oidc-in-fulcio.md?plain=1#L100 is currently returning a 404.

From a quick search, I don't see where this should currently be pointed to.

**Comment by znewman01** [comment]
https://github.com/sigstore/fulcio/blob/main/docs/oid-info.md see #48

**Comment by znewman01** [comment]
Nvm, this is fixed by #46. @ltagliaferri you can close this!
