### ISSUE TITLE
bad link on doc about policy-controller installation

### ISSUE THREAD

**Issue by Nicolas-Peiffer** [sigstore/docs#18]
Hello,
On this web page [policy-controller/overview](https://docs.sigstore.dev/policy-controller/overview/), I noticed a bad link [installation instructions](https://docs.sigstore.dev/policy-controller/overview/installation) (error page not found).

The markdown file with the bad link is this one:
https://github.com/sigstore/docs/blob/ba2468317377e448cdda4b8a51500cf3d700b662/content/en/policy-controller/overview.md?plain=1#L14

I don't know for sure, but the link should probably point toward [content/en/policy-controller/installation.md](https://github.com/sigstore/docs/blob/ba2468317377e448cdda4b8a51500cf3d700b662/content/en/policy-controller/installation.md).

**Comment by ltagliaferri** [comment]
We're having a discussion about trailing slashes here: https://github.com/sigstore/sigstore-website/pull/228

**Comment by Nicolas-Peiffer** [comment]
Okay thank you @ltagliaferri , I did not notice the issue since it was on the other repo. Closing the issue since it is discussed `sigstore/sigstore-website/pull/228`.
