### ISSUE TITLE
Re-arrange sigstore docs so that they are more clear to readers

### ISSUE THREAD

**Issue by jonvnadelberg** [sigstore/docs#191]
**Description**

The current arrangement of sigstore doc is somewhat haphazard and does not lend itself to easy understanding.  I'm proposing a new organization of the material so it flows better with user journeys.

The proposal is written up here:

https://docs.google.com/document/d/1NFxvtQu-tZ07D3aXXslQpYGhaztl6RDPw7L5HPc4-2Y/edit?usp=sharing

This issue is related to https://github.com/sigstore/docs/issues/187#issuecomment-1590055593

@haydentherapper @ltagliaferri @olivekl 

This issue will be fixed with multiple pull requests:

Rearrange existing files to be in the order that is specified in the outline on a group by group level.  

1. About sigtore
2. Signing (was part of cosign)
3. Verifying (was part of cosign)
4. Key management (was part of cosign)
5. Command line interface (new)
6. Certificate authority  (was fulcio)
7. Transparency log (was rekor)
8. Kubernetes policy controller

Edit files so that content matches new headers:

Move all verify information to verify sections.

**Comment by jonvnadelberg** [comment]
One question that came up is what exactly do we want developer users to do with the software?   What information do we want to provide to people to help with the developer journey.

**Comment by olivekl** [comment]
Thanks for this, @jonvnadelberg. I don't think the doc you linked with be accessible to all viewers. Could you copy-paste your proposal into the issue?

**Comment by jonvnadelberg** [comment]
In case people can't access the outline, I'm posting it here.

—-----------------------------------------------SHARED EXTERNALLY---------------------------------------------

Proposed outline for sigstore docs

This outline will try to set up the left window menu item to be based on function and not names.

User Doc
Sigstore
Overview (https://docs.sigstore.dev/ ) & Main concepts (https://docs.sigstore.dev/main-concepts/)
Stability & Security (https://docs.sigstore.dev/api-stability/ & https://docs.sigstore.dev/security/)
Contributing & Community (https://docs.sigstore.dev/contributing/ & https://docs.sigstore.dev/community/)
Support (https://docs.sigstore.dev/support/)
FAQ (https://docs.sigstore.dev/faq/)
History (https://docs.sigstore.dev/history/)
Signing
Overview & Installation (https://docs.sigstore.dev/cosign/overview/ & https://docs.sigstore.dev/cosign/installation/)
OpenID connect signing (https://docs.sigstore.dev/cosign/openid_signing/)
PKCS 11 tokens signing (https://docs.sigstore.dev/cosign/pkcs11/)
Blobs (https://docs.sigstore.dev/cosign/signing_with_blobs/)
Containers (https://docs.sigstore.dev/cosign/signing_with_containers/)
Git support (https://docs.sigstore.dev/cosign/git_support/)
Gitsign (https://docs.sigstore.dev/gitsign/overview/)
Gitsign installation (https://docs.sigstore.dev/gitsign/installation/)
Gitsign usage (https://docs.sigstore.dev/gitsign/usage/)
Inspecting commit signatures (https://docs.sigstore.dev/gitsign/inspecting/)
Signing other types of artifacts (https://docs.sigstore.dev/cosign/other_types/)
Verifying
Signature verification (https://docs.sigstore.dev/cosign/verify/)
Timestamps (https://docs.sigstore.dev/cosign/timestamps/)
In-Toto Attestations (https://docs.sigstore.dev/cosign/attestation/)
Key Management
KMS support (https://docs.sigstore.dev/cosign/kms_support/)
Signing with self-managed keys (https://docs.sigstore.dev/cosign/signing_with_self-managed_keys/)
Importing a key pair (https://docs.sigstore.dev/cosign/import-keypair/)
Hardware-based tokens (https://docs.sigstore.dev/cosign/hardware-based-tokens/)

Command line interface
Cosign command line interface reference guide (this is very long. Put in link to https://github.com/sigstore/cosign/tree/main/doc)


Developer Docs
Cosign Specs
Attestation (https://github.com/sigstore/cosign/blob/main/specs/ATTESTATION_SPEC.md)
Cosign predicate (https://github.com/sigstore/cosign/blob/main/specs/COSIGN_PREDICATE_SPEC.md)
Cosign vulnerability attestation (https://github.com/sigstore/cosign/blob/main/specs/COSIGN_VULN_ATTESTATION_SPEC.md)
SBOM (https://github.com/sigstore/cosign/blob/main/specs/SBOM_SPEC.md)
Signature (https://github.com/sigstore/cosign/blob/main/specs/SBOM_SPEC.md)
Certificate Authority
Fulcio Overview (https://docs.sigstore.dev/fulcio/overview/)
Issuing certificates (https://docs.sigstore.dev/fulcio/certificate-issuing-overview/)
Using OIDC tokens (https://docs.sigstore.dev/fulcio/oidc-in-fulcio/)
Certificate specification (https://github.com/sigstore/fulcio/blob/main/docs/certificate-specification.md)
HSM support (https://github.com/sigstore/fulcio/blob/main/docs/hsm-support.md)
Transparency Log
Overview & Installation (https://docs.sigstore.dev/rekor/overview/ & https://docs.sigstore.dev/rekor/installation/)
Certificate Transparency Log Information (https://github.com/sigstore/fulcio/blob/main/docs/ctlog.md)
Public instance (https://docs.sigstore.dev/rekor/public-instance/)
Sharding (https://docs.sigstore.dev/rekor/sharding/)
Command line interface (https://docs.sigstore.dev/rekor/CLI/)
Pluggable types (https://docs.sigstore.dev/rekor/pluggable-types/)
Signing and uploading other pluggable types (https://docs.sigstore.dev/rekor/sign-upload/)
Verifying transparency log binaries (https://docs.sigstore.dev/rekor/verify-release/)

Kubernetes Policy Controller
Overview (https://docs.sigstore.dev/policy-controller/overview/)
Installation (https://docs.sigstore.dev/policy-controller/installation/)
Sample policies (https://docs.sigstore.dev/policy-controller/sample-policies/)

**Comment by jonvnadelberg** [comment]
@olivekl @haydentherapper @ltagliaferri 

Hi there.  If there are no comments on the structure and organization of the docs, I'll go ahead and start working on it this week.

**Comment by ltagliaferri** [comment]
Hi @jonvnadelberg, I don't have access to the doc (you can make it public), but am curious if there is any rationale behind the organization that you can provide so we can weigh in more about the why than the what?

**Comment by jonvnadelberg** [comment]
Hi @ltagliaferri  I just granted you access to it.   You should be able to see it now.  

The rationale behind this is to organize the documentation by function and not the names of modules, and also to try and place document in some semblance of an order that mirrors the user and developer experiences.  

That's the idea anyway.   To try and make it easier for people to understand and learn how to use the product, depending on their role.

**Comment by olivekl** [comment]
Hi @ltagliaferri, it looks like @jonvnadelberg copied the contents of the doc into [this comment](https://github.com/sigstore/docs/issues/191#issuecomment-1601379176). 

As for the why, the goal is to organize the docs in a way that more closely follows the primary user journeys. A user is likely to land on the docs with a goal such as "I want to verify a signature" or "I want to sign a blob," not "I want to read about Fulcio." The current organization is structured around tooling and what goes on under the hood, which makes sense from the point of view of someone developing Sigstore; most users, though, will look for information based on what it is they want to accomplish. The purpose of the proposed organization is to match those user goals more clearly. 

There's more of an explanation and invitation for discussion about user journeys in the [Issue #187 (comment)](https://github.com/sigstore/docs/issues/187#issuecomment-1590055593) that's linked above.

**Comment by jonvnadelberg** [comment]
updates merged into base closing issue.
