### ISSUE TITLE
Broken Link to Keyless Signatures

### ISSUE THREAD

**Issue by lukas-mika-maersk** [sigstore/docs#202]
**Description**

On page "[cosign --> Signing Containers](https://docs.sigstore.dev/cosign/signing_with_containers/)" ([file](https://github.com/sigstore/docs/blob/main/content/en/cosign/signing_with_containers.md)) the link to "Keyless Signatures" ([link](https://docs.sigstore.dev/cosign/keyless)) is broken and returns a HTTP404.

I _assume_ it shall point to "[cosign --> OpenID Connect signing](https://docs.sigstore.dev/cosign/openid_signing/)" ([file](https://github.com/sigstore/docs/blob/main/content/en/cosign/openid_signing.md)) instead.

**Version**

Cosign Public Documentation

**Comment by lukas-mika-maersk** [comment]
Happy to raise a PR, in case my assumption is confirmed.

**Comment by smythp** [comment]
I think you're correct, probably the result of a file rename. Created a PR to resolve.
