### ISSUE TITLE
Shouldn’t that be ‘Signed materials’ instead of ‘Signing materials’

### ISSUE THREAD

**Issue by Santosh1176** [sigstore/docs#21]
**Description**

in the first paragraph of Home page, while introducing Sigstore there is a sentence stating: `Signing materials are then stored in a tamper-resistant public log.`

Shouldn’t that be: `Signed materials are then stored in a tamper-resistant public log.`?

**Version**

**Comment by znewman01** [comment]
I think this is actually mostly correct as written: the _signed_ materials often _don't_ wind up in the log. For example, see this [HashedRekord entry](https://rekor.tlog.dev/?uuid=24296fb24b8ad77ad18ef3ab2ce3aa01d6b66b3edac9e65c3f1c0caacfcc82faa321a26350209b9e): if you look at "raw body," the signed content doesn't appear anywhere in there.

If you interpret "signing materials" to mean the public key and certificate, those *do* wind up in the log. That said, when I read "signing materials" I also think about the *private* signing key, which certainly doesn't end up in the log. But I think that's a minor point.

@Santosh1176 does that make sense? Can you think of a clearer way to word it?

**Comment by Santosh1176** [comment]
> If you interpret "signing materials" to mean the public key and certificate

Got that, Thanks for the clarification. As a beginner to the project, I should have discussed it on slack beforehand.
Thanks again, I'll close this issue.
