### ISSUE TITLE
Code block writing follows Markdownlint - MD014 specification

### ISSUE THREAD

**Issue by normal-coder** [sigstore/docs#217]
**Description**

In best practice, writing Markdown documents is recommended to follow the [MarkdownLint](https://github.com/DavidAnson/markdownlint) specification.

In `content/en/signing/pkcs11.md`, `content/en/key_management/overview.md`, `content/en/key_management/hardware-based-tokens.md`, there are many code blocks with only commands `$` is used in front of the command, which does not conform to the specification [MD014 - Dollar signs used before commands without showing output](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md014.md ), it is recommended to improve the document for a better reading experience.

**Comment by smythp** [comment]
While we might consider running a linter on the docs, these do not seem like high-quality PRs.

**Comment by normal-coder** [comment]
> While we might consider running a linter on the docs, these do not seem like high-quality PRs.

这个动作如果从外部贡献，我想单次的 Pull Request 会因为涉及太多的变更被拒绝，因此我尝试拆解成多个 Pull Request，希望能推动现有工程的结构规范，这将有助于后续在 CI 上添加 linter 工程，如果现在添加的话，我理解将会阻断很长一段时间的 code review（我试着 check 了下，需要改动的位置很多，）

**Comment by smythp** [comment]
Broadly speaking, I think anything that could be handled by running linters or other automation should be considered as part of improving CI, which is out of scope for creating a PR here. If you're interested in questions of formatting, I suggest getting involved by attending community meetings and proposing adding new processes to CI.

https://github.com/sigstore/community

Additionally, we have many active issues open, some of which have quite a small scope and would make great first PRs, such as fixing broken links. It's also policy here to refer to an open issue when proposing a PR, so I recommend starting with issues if you'd like to start contributing.

Thank you, and have a good week.
