### ISSUE TITLE
Add a note that RSA keys are not supported by Cosign

### ISSUE THREAD

**Issue by toddysm** [sigstore/docs#23]
**Description**

Some key management systems may default to RSA type keys. We should add a note to https://docs.sigstore.dev/cosign/key-generation that RSA keys are not supported.

**Comment by anderssonw** [comment]
+1 :)

**Comment by anderssonw** [comment]
Agreed, ran into the same issue and made #79.

**Comment by Neilblaze** [comment]
@toddysm can I take a shot if this is up for grabs?
