### ISSUE TITLE
Bring back redirects

### ISSUE THREAD

**Issue by ltagliaferri** [sigstore/docs#230]
With the migration we lost some redirects and need to bring them back. 

Former file: https://github.com/sigstore/docs/pull/210/files#diff-fd40fde62534b781806d746f82ba621d39c640f85029c1524582d4b137701cfe

Netlify documenation: https://docs.netlify.com/routing/redirects/

**Comment by smythp** [comment]
I'll look into this, thanks!

**Comment by smythp** [comment]
Reopening because the redirects still aren't working. I suspect I know what the issue is, however. I'm going to create a draft PR and do some testing.
