### ISSUE TITLE
Add docs to verify Cosign releases

### ISSUE THREAD

**Issue by toddysm** [sigstore/docs#25]
**Description**

Cosign is the tool used to verify signatures but for the first installation of Cosign there is no way to verify the downloaded/installed binaries. Documentation similar to https://docs.sigstore.dev/rekor/verify-release would be helpful for people who install Cosign for the first time.

**Comment by FavourDaniel** [comment]
Hi, @toddysm Are you working on this? If not, I would like to take it up.

**Comment by toddysm** [comment]
@FavourDaniel it is up for grabs

**Comment by FavourDaniel** [comment]
@toddysm Thank you, will start working on it right away

**Comment by Neilblaze** [comment]
I think we can close this issue as the proposed changes have been already rolled out in the recent update of cosign's [docs](https://github.com/sigstore/docs/blob/main/content/en/cosign/installation.md).

**Comment by haydentherapper** [comment]
Correct, this can be closed
