### ISSUE TITLE
Inaccurate ARIA label for Navigation Landmark

### ISSUE THREAD

**Issue by krishnabodawala** [sigstore/docs#252]
## Description

All pages on the Website are marked up by 2 Navigation landmarks using HTML. However, the top landmark has been given an ARIA label as Main navigation, which breaks the hierarchy of landmarks, and create ambiguity for screen reader users.
Recommendation  Edit ARIA label to 'Primary' from 'Main Navigation'

## Note

The relevant WCAG success criteria is[1.3.1]( https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html )

References Accessibility Audit #245

## Background

Test performed by Krishna Bodawala, accessibility consultant for Iota.

**Comment by smythp** [comment]
Resolved in #256

**Comment by krishnabodawala** [comment]
Yes, I noticed that.

On 10/9/23, Patrick Smyth ***@***.***> wrote:
> Resolved in #256
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/sigstore/docs/issues/252#issuecomment-1753891478
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
KRISHNA BODAWALA
+(1)551-263-5182
