### ISSUE TITLE
Redundant use of word "Navigation" in ARIA label

### ISSUE THREAD

**Issue by krishnabodawala** [sigstore/docs#253]
## Description

Using the word "Navigation" to the ARIA label for the element marked up as HTML navigation, makes the screen reader announce it twice , for a screen reader user, it can get tiresome.

## Note

The relevant WCAG success criteria is[1.3.1]( https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html )
Reference Accessibility Audit #245

## Background

Test performed by Krishna Bodawala Accessibility Consultant Iota

**Comment by smythp** [comment]
@krishnabodawala  Pretty sure this is resolved, but can you double check this preview to see if it fixes the main navigation redundency?

https://deploy-preview-256--docssigstore.netlify.app/
