### ISSUE TITLE
Investigate a way to preview docs before merging pull request

### ISSUE THREAD

**Issue by hayleycd** [sigstore/docs#326]
Is there a way (perhaps using a github action and github pages) that we could preview changes to the docs before merging pull requests?

**Comment by smythp** [comment]
Hi Hayley, this should already be instituted, though let me know if I'm not understanding your request. When you create a PR,  NetlifyBot responds with a table that includes a deploy log and links to previews for desktop and mobile. For example, the below link is to the PR for the cosign reorg you created last week:

https://deploy-preview-323--docssigstore.netlify.app/

If you push a new commit on the PR, the bot will update the previews.

Let me know if I'm missing something about hte request here. :)
