### ISSUE TITLE
Rekor operator is not real installation method

### ISSUE THREAD

**Issue by iwankgb** [sigstore/docs#37]
**Description**

Rekor installation docs claim that:

> There are a few ways you can deploy a Rekor Server:
> 
> 1. We have a [docker-compose](https://github.com/sigstore/rekor/blob/main/docker-compose.yml) file available
> 2. A [kubernetes operator](https://github.com/sigstore/rekor-operator)
> 3. Alternatively, you can build a Rekor server yourself.

I believe this is misleading as the operator does nothing and can't be used to install Rekor. There for I recommend removing point number 2 from the list mentioned above.

**Version**

`main`

**Comment by haydentherapper** [comment]
We should remove all references to Rekor-operator, it’s now a deprecated repo
