### ISSUE TITLE
Jumbled sentence in How Sigstore Works

### ISSUE THREAD

**Issue by bishal7679** [sigstore/docs#51]
**Description**

Here I found one sentence which is jumbled and not creating any sense

## Current behaviour
`This checks you are who you say you are using OpenID Connect`

if we update with this might be meaningful

`This checks who you are using OpenID Connect`

![Dec-12-22-01](https://user-images.githubusercontent.com/70086051/209982482-0cb3317e-1731-42e9-920b-f18364e956da.png)

**Comment by ro4i7** [comment]
@ltagliaferri  What about this,

'When you use Fulcio, Sigstore asks for a certificate from our main authority to confirm that you are the author. It uses your email address to check your identity through OpenID Connect. Fulcio then gives you a time-stamped certificate, which proves that you are signed in and that it is actually you.'
