### ISSUE TITLE
Add Node Version to README

### ISSUE THREAD

**Issue by ChrisJBurns** [sigstore/docs#53]
Currently, when you clone this repository as a fresh project and run a `yarn dev` (after the `yarn install`), you get the `Error: error:0308010C:digital envelope routines::unsupported` error if you are running Node v17. We should probably add a little note in the README detailing that Node v16 is required. Saves troubleshooting time of new contributors?

**Comment by Neilblaze** [comment]
@ChrisJBurns Is this up for grabs? If yes, can you assign me this? Thanks!

**Comment by ChrisJBurns** [comment]
@Neilblaze  Go for it :)
