### ISSUE TITLE
Improve documentation regarding key types

### ISSUE THREAD

**Issue by anderssonw** [sigstore/docs#79]
**Description**

I wanted to use Google KMS instead of generating keys using cosign, and for testing purposes I just used an old key of type `4096 bit RSA key PSS Padding - SHA256 Digest`. This returned the following error: `main.go:74: error during command execution: signing [[IMAGE@sha256:DIGEST](http://IMAGE@DIGEST)]: signing digest: [POST /api/v1/log/entries][400] createLogEntryBadRequest  &{Code:400 Message:error processing entry: verifying signature: crypto/rsa: verification error}`. I used the `Elliptic Curve P-256 keySHA256 Digest` type in Google KMS instead, which worked fine.

I think documentation regarding which kind of keys are allowed for signing should be improved, because this was not entirely obvious. I could only find `cosign differs in that it signs with ECDSA-P256 keys instead of PGP, and stores signatures in the registry.` in the FAQ, which is why I tried that type of key, but looking in the FAQ was not my first choice.

**Comment by haydentherapper** [comment]
Hey @anderssonw, the issue isn't that RSA isn't supported, it's just that RSA PSS keys are not supported. You can work around this by generating RSA PKCS#1.5 keys. I've filed an issue, https://github.com/sigstore/sigstore/issues/1066, to track supporting this.
