### ISSUE TITLE
rewrite cosign quick start guide

### ISSUE THREAD

**Issue by jonvnadelberg** [sigstore/docs#93]
The current quick start guide contains some information that needs updating.   Doc should be rewritten so it is more relevant to user's needs.

**Comment by FavourDaniel** [comment]
@jonvnadelberg please is anyone working on this? I would like to take it up

**Comment by ltagliaferri** [comment]
@FavourDaniel it looks like there is a PR open for this work already

**Comment by FavourDaniel** [comment]
@ltagliaferri Alright then. I'll look for a different issue
