### ISSUE TITLE
Add instructions for verifying Cosign release

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/docs#95]
**Description**

The Cosign binary is signed both with keyless signing and an artifact key. You first need to verify Cosign with the artifact key, since you will need Cosign to verify the keyless signature.

https://github.com/sigstore/fulcio/pull/1079/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R78 includes instructions for Fulcio. This should be copied over for verifying Cosign binaries.

**Comment by Queen-codes** [comment]
Hi, @haydentherapper. I'm interested in working on this and I need some guidance. Do you mean the instructions for Fulcio should be copied into the Cosign binaries?

**Comment by haydentherapper** [comment]
Thank you! The cosign binary is signed the same way as the fulcio binary, with the artifact key mentioned in the linked documentation. The instructions I linked should be copied over to the page on installing cosign, updating any references to “fulcio” to instead be “cosign”.

**Comment by Queen-codes** [comment]
okay, thank you very much. I would get right into it

**Comment by Queen-codes** [comment]
Hi, @haydentherapper. I've been going through the docs repo and the website and I am kind of stuck on which .md file in the cosign folder I would be modifying to solve the issue or would I be creating a new one?

**Comment by Queen-codes** [comment]
Hi, @haydentherapper. I've been going through the docs repo and the website and I am kind of stuck on which .md file in the cosign folder I would be modifying to solve the issue or would I be creating a new one?

**Comment by haydentherapper** [comment]
https://github.com/sigstore/docs/blob/main/content/en/cosign/installation.md would work

**Comment by Queen-codes** [comment]
alright. thank you.

**Comment by Queen-codes** [comment]
Hi @haydentherapper. I made a pull request for this issue already. Please kindly review and let me know if i need to make any changes.

**Comment by Neilblaze** [comment]
@haydentherapper I think we can close this issue as it was fixed in https://github.com/sigstore/docs/pull/100. Thanks!
