### ISSUE TITLE
Reposition toggle-button for Dark Mode in Docs

### ISSUE THREAD

**Issue by Neilblaze** [sigstore/docs#96]
### **Description**

Most users nowadays prefer surfing docs with `Dark-Mode` **_enabled_**. But, in the current design, the user has to first scroll down to the bottom & then can access the toggle button to switch between themes, which I believe is a bad UX.

![image](https://user-images.githubusercontent.com/48355572/227808026-0de6d64e-e78b-4a06-b61f-5b3dca176bd6.png)

### **Solution**

I propose a solution where we can shift the button to the sticky navbar which will remain fixed even if we scroll down, so that the user can switch between themes anytime they want. Plus, we can also shift the "Built with Nuxt" promo to the sidebar to make to reduce unnecessary space wastage on the viewport. 

![image](https://user-images.githubusercontent.com/48355572/227808069-e49b0858-6eba-4250-b2c1-30fa4719865d.png)

---

**Final look** 👇🏼
 
![image](https://user-images.githubusercontent.com/48355572/227808094-5f6cfc11-838e-4055-aa7e-e9b3e05ad06a.png)

> **P.S. : If this issue is validated & approved, I'd love to contribute. Additionally, I do have a similar design in mind, following the same approach for responsive mode (i.e. mobile view).**

**Comment by Neilblaze** [comment]
@ltagliaferri thoughts on this?

**Comment by ltagliaferri** [comment]
Hi @Neilblaze, the docs site is automatically set up to run dark or light mode based on system preferences. FWIW, we are thinking about replatforming the site in the near to mid-term future. I don't think this is an urgent need as docs are the more important concern, but if you feel strongly about it you can certainly open a PR.

**Comment by Neilblaze** [comment]
Closed as of now, refer to [this](https://github.com/sigstore/docs/issues/107#:~:text=Besides%2C%20all%20this%20hassle%20is%20also%20the%20same%20reason%20why%20%2396%20can%27t%20be%20performed%20either%2C%20as%20to%20create%20changes%2C%20one%20has%20to%20directly%20perform%20it%20on%20the%20library%20files%20itself%2C%20which%20isn%27t%20possible%20without%20importing%20locally.)!
